### ISSUE TITLE
Error when searching for default system name

### ISSUE THREAD

**Issue by Zulu-Inuoe** [mmgeorge/sly-asdf#1]
When invoking any `sly-asdf-*` command that looks for the default system name from the current dir, and being on a dir that's relatively "far" from a system I receive this error:

```
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
  file-name-extension("$Recycle.Bin")
  (string-equal "asd" (file-name-extension file))
  (closure ((fname . "c:/") (directory . "c:/") sly-asdf--contrib sly-asdf--path t) (file) (string-equal "asd" (file-name-extension file)))("$Recycle.Bin")
  cl--position(nil ("$Recycle.Bin" "AMD" "Config.Msi" "Documents and Settings" "OpenSSL-Win64" "PerfLogs" "Program Files" "Program Files (x86)" "ProgramData" "Python27" "Recovery" "System Volume Information" "Users" "Windows" "hiberfil.sys" "pagefile.sys" "sbcl" "sbcl-test" "swapfile.sys") 0 nil nil)
  cl-position(nil ("$Recycle.Bin" "AMD" "Config.Msi" "Documents and Settings" "OpenSSL-Win64" "PerfLogs" "Program Files" "Program Files (x86)" "ProgramData" "Python27" "Recovery" "System Volume Information" "Users" "Windows" "hiberfil.sys" "pagefile.sys" "sbcl" "sbcl-test" "swapfile.sys") :if (closure ((
```

I think there needs to be either a reasonable 'best effort' default (probably don't want to end up scanning entire file system) or an implementation that doesn't break the stack.

Works fine when visiting a typical lisp file near a system though.

Thanks!

**Comment by mmgeorge** [comment]
@Zulu-Inuoe thanks for reporting this! Ideally this would just display the package selection menu without any default when it cannot find a system to put as the default.

**Comment by mmgeorge** [comment]
@Zulu-Inuoe sorry for being ridiculously slow with this. 

I think [this](https://github.com/mmgeorge/sly-asdf/pull/2) should solve your issue -- adds a [default max depth of 10](https://github.com/mmgeorge/sly-asdf/blob/master/sly-asdf.el#L38). If a system cannot be found, the browser will be brought up without any default. Tested on Debian, let me know if you are still have any problems on Windows.

**Comment by Zulu-Inuoe** [comment]
Just tested with the latest release. Works great, thank you!
