### ISSUE TITLE
Add command and repl shortcut for asdf:test-system

### ISSUE THREAD

**Issue by mmgeorge** [mmgeorge/sly-asdf#13]
Add command and repl shortcut for `asdf:test-system`

_Originally posted by @maruks in https://github.com/mmgeorge/sly-asdf/issues/8#issuecomment-536972671_

**Comment by mmgeorge** [comment]
FYI @maruks @Ambrevar just installed this. Let me know if you any issues.

**Comment by Ambrevar** [comment]
Fantastic, thanks!

**Comment by maruks** [comment]
works very well,  thank you
