### ISSUE TITLE
Compilation/load notes not reporting correctly

### ISSUE THREAD

**Issue by Zulu-Inuoe** [mmgeorge/sly-asdf#15]
On SBCL, 1.5.8 the bundled ASDF is not yet at the latest ASDF version, and `dependency-not-done` does not exist.

I tracked this down to 
https://github.com/mmgeorge/sly-asdf/blob/master/slynk-asdf.lisp#L300

I don't have time to look into it right now, but it'd be great if this could be made to work with older ASDF's

**Comment by mmgeorge** [comment]
Whoops yes, definitely shouldn't be breaking such a recent version of sbcl / asdf. Need to get around to adding CI for ASDF 3.0+. Working on a fix now

**Comment by mmgeorge** [comment]
@Zulu-Inuoe I merged a fix that comments out the symbol for now. I also added a simple [github action](https://github.com/mmgeorge/sly-asdf/blob/master/.github/workflows/ci.yml) to check for undefined symbols associated with sbcl 1.4.2. (asdf 3.3.1) Will look at potentially testing earlier versions. Let me know if you are still running into any issues

**Comment by Zulu-Inuoe** [comment]
Thanks! seems to work fine here. Good to close this issue?
Unless you want to keep it open

**Comment by Zulu-Inuoe** [comment]
Actually @mmgeorge now I'm seeing this upon loading a system through `sly-asdf`:

![image](https://user-images.githubusercontent.com/1526310/74387927-f0ae3200-4dc7-11ea-8bd8-94552a847757.png)

I'm eg it marks it as failed even though no warnings or errors were reported. Guessing this is a bug?

**Comment by Zulu-Inuoe** [comment]
And one final thing - it looks like warnings/notes/errors are now gathered up as if they were in the `*sly-source*:1:1:` "file", which unfortunately means I can't jump between them (a key reason why I like `sly-asdf`

**Comment by mmgeorge** [comment]
Yes I noticed this as well -- I think I know what's causing this. If I can't figure it out today, I'll revert back to the last stable version.

**Comment by mmgeorge** [comment]
@Zulu-Inuoe for errors being reported as being located in `*sly-source*:1:1`, is this occuring when you are loading a system? I.e., you're not seeing this:

![test](https://user-images.githubusercontent.com/16738762/74394223-04a26580-4dc1-11ea-943b-da4797b4b010.gif)

**Comment by mmgeorge** [comment]
Compilation reporting should now be fixed ... still trying to reproduce the other issue you're seeing. Maybe due to a newer version of sly? Will investigate further tomorrow.

**Comment by Zulu-Inuoe** [comment]
@mmgeorge Thanks! Looks like the false 'failures' are gone.
I can't replicate the issue collecting notes. If I see it again and come up with some reproduction steps I'll write up another issue.

**Comment by mmgeorge** [comment]
Sounds good!
