### ISSUE TITLE
Misleading errors if file fails to compile

### ISSUE THREAD

**Issue by Zulu-Inuoe** [mmgeorge/sly-asdf#29]
Hello!

I noticed that if I load a system through sly-asdf, then if a file fails to compile properly, it continues loading the rest of the system.

This can lead to a top of misleading errors arising from failing to load a file you depend on.
For example:

with `foo.asd`: 
```lisp
(defsystem #:foo
  :serial t
  :components
  ((:file "foo")
   (:file "bar")))
```
a `foo.lisp`:
```lisp
(defpackage #:foo
  (:use #:cl)
  (:export #:foo))
(in-package #:foo)

(defun foo ()
  t)
(defun foo ()
  nil)
```
and `bar.lisp`:
```lisp
(defpackage #:bar
  (:use #:cl))
(in-package #:bar)

(foo:foo)
```

loading the system from sly-asdf's load-system results in these compiler notes:
```
cd c:/Users/zulu/common-lisp/foo/
3 compiler notes:

bar.lisp:1:1:
  error: The function FOO:FOO is undefined.

foo.lisp:1:1:
  error: 
    Couldn't load
    #P"C:/Users/zulu/AppData/Local/cache/common-lisp/sbcl-1.5.8-win-x64/C/Users/zulu/common-lisp/foo/foo.fasl":
    file does not exist.

foo.lisp:10:1:
  warning: 
    Duplicate definition for FOO found in one file.
    --> PROGN 
    ==>
      (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN 'FOO:FOO T NIL NIL))
    

Compilation failed.
```
So it looks like it:
1. Is trying to load foo.fasl, even though compiling foo.lisp failed
2. Trying to load bar.lisp, even though compiling/loading foo failed

I would instead expect the compilation log to look like this:
```
cd c:/Users/zulu/common-lisp/foo/
1 compiler notes:

foo.lisp:10:1:
  warning: 
    Duplicate definition for FOO found in one file.
    --> PROGN 
    ==>
      (EVAL-WHEN (:COMPILE-TOPLEVEL) (SB-C:%COMPILER-DEFUN 'FOO:FOO T NIL NIL))
    

Compilation failed.
```

**Comment by mmgeorge** [comment]
Hmm so basically you would prefer for loading to stop on the first failure? Or would the ideal scenario be that it stops loading dependents of that specific file, but still loads files that do not depend on it? Probably only the first could be implemented in the general case where load dependencies aren't specified directly. The concept behind the way it is currently is to try and find all the existing errors, however it does cause cascading failures. 

I can look at changing this to stop on the first failure. Probably I can make that the default and potentially add a flag to opt into the current behavior, as perhaps the way it is now is less intuitive. 

I'll take a look at this next week (will unfortunately be busy this weekend with work related stuff)

**Comment by Zulu-Inuoe** [comment]
I was thinking it would behave the same way `asdf:load-system` works, in that it breaks at the first error. Over there it'll drop into the debugger, but I think it'd be reasonable to just abort and present the error.
The whole idea with non-dependencies loading etc sounds a bit niche since I don't see much use in working with a half-broken system.

**Comment by mmgeorge** [comment]
@Zulu-Inuoe installed, let me know if things still aren't working as you would expect.
