### ISSUE TITLE
Depropertize the system

### ISSUE THREAD

**Issue by Ambrevar** [mmgeorge/sly-asdf#32]
With ws-butler, `,load-system RET whatever` crashes the Lisp.

Simple fix:

```elisp
(defun sly-asdf-read-system-name (&optional prompt default-value)
  "Read a system name from the minibuffer, prompting with PROMPT.
If no DEFAULT-VALUE is given, one is tried to be determined: if
DETERMINE-DEFAULT-ACCURATELY is true, by an RPC request which
grovels through all defined systems; if it's not true, by looking
in the directory of the current buffer."
  (let* ((completion-ignore-case nil)
         (prompt (or prompt "System"))
         (system-names (sly-eval `(slynk-asdf:list-asdf-systems)))
         (default-value
           (or default-value (sly-asdf-find-current-system) (car sly-asdf-system-history)))
         (prompt (concat prompt (if default-value
                                    (format " (default `%s'): " default-value)
                                  ": "))))
    (let ((history-delete-duplicates t)
          (result (completing-read prompt (sly-asdf-bogus-completion-alist system-names)
                                   nil nil nil
                                   'sly-asdf-system-history default-value)))
      (when result 
        (substring-no-properties result)))))
```

Fixes https://github.com/joaotavora/sly/issues/311.

See also https://github.com/joaotavora/sly/issues/370 for a more general fix, but I guess this patch can't do any harm.

**Comment by joaotavora** [comment]
Personally, I don't think we should sprinkle `substring-no-properties` in every contrib just because `ws-butler` is hijacking the completion system and SLY isn't dealing well with it.  `ws-butler` should stop doing that, and SLY should be less susceptible, but I'd let these poor contribs out of the fray.

**Comment by Ambrevar** [comment]
Agreed, although here it's (almost) a 1-liner defensive fix.

**Comment by Ambrevar** [comment]
SLY is now less susceptible on master, so this should not be an issue anymore.

@mmgeorge Feel free to close this, as you like :)

**Comment by mmgeorge** [comment]
Sorry for the late response! In that case I'll close this for now, but feel free to re-open if you are still running into any issues.
