### ISSUE TITLE
Logical pathnames are not translated

### ISSUE THREAD

**Issue by Ambrevar** [mmgeorge/sly-asdf#40]
Reporting warnings and errors when compiling logical pathnames results in the `*sly-compilation*` buffer listing the logical pathnames (e.g. `SYS:SRC;foo.lisp`) instead of the physical path.  Calling `next-error` or clicking on the compiler note then results in the source not being found.

Easy fix:

```lisp
(defun replace-location-if-error (location)
  (if (and (eq (car location) :error)
           *current-source-file*)
      (slynk-backend:make-location
       `(:file ,(namestring (translate-logical-pathname (asdf:component-pathname *current-source-file*))))
       `(:position 0))
      location))
```

**Comment by Ambrevar** [comment]
Friendly ping @mmgeorge :)
Should I send a pull request?

**Comment by mmgeorge** [comment]
Sorry @Ambrevar, I don't do much common lisp programming these days, so I've been slow to get to this. 

PRs always welcome!

**Comment by Ambrevar** [comment]
Thanks and done with #41 :)
