### ISSUE TITLE
doesn't work after SLY package upgrade

### ISSUE THREAD

**Issue by maruks** [mmgeorge/sly-asdf#8]
Invalid protocol message: Symbol "AUTODOC" not found in the SLYNK package.

**Comment by maruks** [comment]
versions:

sly               20190928.1230 dependency            Sylvester the Cat's Common Lisp IDE
sly-asdf       20190928.1930 dependency            ASDF system support for SLY

**Comment by mmgeorge** [comment]
Hmm thanks for reporting this, I'll take a 👀

**Comment by mmgeorge** [comment]
@maruks I can't seem to reproduce on a fresh vm with debian 10 + emacs 26.3 + latest sly/sly-asdf (though I am getting an undefined function `first` error which I'll fix, not sure if this was somehow removed). Can you give me some details about your enviornment?

**Comment by mmgeorge** [comment]
Just got this error randomly. Are you able to repro this reliably? Will need to take a look and see what changed in `sly`

```
Invalid protocol message:
Symbol "AUTODOC" not found in the SLYNK package.

Line: 1, Column: 12, File-Position: 12
Stream: #<SB-IMPL::STRING-INPUT-STREAM {10047F09E3}>
(:emacs-rex (slynk:autodoc (quote nil) :print-right-margin 122) nil 1 4)
```

**Comment by maruks** [comment]
I can't reproduce it today.  I enabled sly-asdf and it works just fine.

**Comment by maruks** [comment]
please add command and repl shortcut for asdf:test-system

**Comment by mmgeorge** [comment]
Closing in favor of https://github.com/mmgeorge/sly-asdf/issues/13. Sorry for the long delay on this, should be straightforward. Will look into this tomorrow.
